Deprecated "Token"
Error: You are accessing the global "Token" which is now namespaced under foundry.canvas.placeables.Token
Deprecated since Version 13