Fix warnings migrations (#4845)
* Fix Warnings because old bad migration documents, to avoid warning:
TypeError: Failed data migration for FeatData: source.uses?.max?.includes is not a function at #migrateUses (activities.mjs:170:28) at ActivitiesTemplate.migrateActivities (activities.mjs:159:36) at FeatData._migrateData (feat.mjs:174:24) at FeatData.migrateData (abstract.mjs:240:10) at FeatData.migrateDataSafe (foundry-esm.js:10695:14) at TypeDataField.migrateSource (foundry-esm.js:9837:22) at

* Reverting change of name in package lock

* Reverting change of name in package lock

* Check null point

And remove the test when is to create the object source.uses

* Fix atribuition cases

Fix atribuition cases

* Add  the missing  if

Fix the missing if

* Add the missing if

Add the missing if

* Update module/data/item/templates/activities.mjs

Be sure to avoid code style changes like this.

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* chain the function

We should just be able to optionally chain on the function itself (you are also only checking whether max has includes on the top-level source, which isn't necessarily true for the max within this loop):

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* style fix

style fix

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* style fix

style fix

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* Unecessary check

On this one the optional chaining can be ditched altogether - by this point in the code we know sources.uses.recovery exists, which means sources.uses necessarily exists

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* Style fix

Style fix

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* Check if function is null directly

Check if function is null directly

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* Forbiden check in atribuition

Co-authored-by: Jeff Hitchcock <github444@command-center.org>

* remove undeclared variable 

remove undeclared variable

* Fixes thanx  @roth-michael

* Update module/data/item/templates/activities.mjs

The source always be filled

Co-authored-by: roth-michael <72220390+roth-michael@users.noreply.github.com>

* Update activities.mjs

Source allways exist

* Update activities.mjs

Removing  unnecessary lines

* Fix code formatting

* Fix remaining unnecessary checks

* Final fixes?

---------

Co-authored-by: Jeff Hitchcock <github444@command-center.org>
Co-authored-by: roth-michael <72220390+roth-michael@users.noreply.github.com>